/*
-- Query: select * from medicina
LIMIT 0, 1000

-- Date: 2022-07-01 18:47
*/
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (60,'A','Sacituzumab govitecan');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (61,'B','Sacubitril/Valsartan');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (62,'C','Salmeterol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (63,'D','Salsalato');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (64,'A','Sapropterin');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (65,'B','Saquinavir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (66,'B','Sareciclina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (67,'B','Sargramostim');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (68,'D','Sarilumab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (69,'D','Satralizumab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (70,'D','Saxagliptina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (71,'D','Scopolamine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (72,'D','Secnidazol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (73,'C','Secobarbital');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (74,'C','Secukinumab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (75,'C','Selegilina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (76,'C','Selenium sulfide');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (77,'C','Selexipag');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (78,'C','Selinexor');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (79,'C','Semaglutida');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (80,'C','Sertralina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (81,'A','Sevelamer');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (82,'A','Sildenafilo');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (83,'A','Silodosina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (84,'A','Siltuximab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (85,'A','Silver sulfadiazine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (86,'A','Simeprevir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (87,'A','Simethicone');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (88,'A','Simvastatina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (89,'A','Sipuleucel-T');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (90,'B','Sirolimus');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (91,'B','Sitagliptina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (92,'B','Sodium oxybate');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (93,'B','Sodium phosphates');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (94,'B','Sodium polystyrene sulfonate');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (95,'B','Sodium tetradecyl sulfate');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (96,'B','Sodium thiosulfate');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (97,'C','Sofosbuvir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (98,'C','Sofosbuvir/velpatasvir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (99,'C','Sofosbuvir/velpatasvir/voxilaprevir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (100,'C','Solifenacina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (101,'C','Solriamfetol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (102,'C','Somatropin');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (103,'D','Sonidegib');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (104,'D','Sorafenib');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (105,'D','Sotalol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (106,'D','Spinosad');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (107,'D','Spiramycin');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (108,'D','Stavudine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (109,'D','Streptozocin');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (110,'C','Succimer');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (111,'C','Succinylcholine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (112,'C','Sucralfato');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (113,'C','Sufentanilo');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (114,'C','Sulconazol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (115,'C','Sulfacetamida');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (116,'A','Sulfadiazine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (117,'A','Sulfadoxine/pyrimethamine');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (118,'A','Sulfasalazina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (119,'A','Sulindaco');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (120,'A','SumatriptÃ¡n');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (121,'A','Sunitinib');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (122,'A','Suramin');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (123,'A','Suvorexant');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (124,'AB','Aspirina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (125,'B','Omeprazol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (126,'B','Lexotiroxina sÃ³dica');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (127,'B','Ramipril');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (128,'B','Amlodipina');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (129,'B','ParacetamolÂ ');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (130,'B','Aciclovir');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (131,'B','Adalimumab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (132,'B','Adapaleno');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (133,'B','Calcitriol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (134,'B','Butorphanol');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (135,'B','Dinoprostone');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (136,'D','Dinutuximab');
INSERT INTO `` (`Id_Medicina`,`Tipo`,`Descripcion`) VALUES (137,'D','Etodolaco');
